name: Build Docker images

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [6]
    env:
      repo: "govpf/redis"
    steps:

    - name: Checkout
      uses: actions/checkout@v3.3.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1

    - name: gpg hack
      run: wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash

    - name: Build and push
      uses: docker/build-push-action@v4.0.0
      with:
        context: ./${{ matrix.versions }}
        file: ./${{ matrix.versions }}/Dockerfile
        platforms: linux/amd64
        pull: true
        push: false
        tags: |
          ${{ env.repo }}:${{ matrix.versions }}
